version: '1'
name: school-system

services:
  Postgres:
    image: postgres:latest
    container_name: Postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./Docker/postgres-data:/var/lib/postgresql/data