version: '1'

services:
  RDBMS:
    image: postgres:latest
    restart : always
    container_name: RDBMS
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: