version: '1'
name: school-system

services:
  Postgres:
    image: postgres:latest
    restart: always
    container_name: Postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    extra_hosts:
      - "nestjs:172.25.0.11"
      - "postgres:172.25.0.12"
    networks:
      bigdata:
        ipv4_address: 172.25.0.12

  nestjs:
    build:
      context: ./
      dockerfile: nestjs.dockerfile
    restart: always
    container_name: nestjs
    ports:
      - 3000:3000
    extra_hosts:
      - "nestjs:172.25.0.11"
      - "postgres:172.25.0.12"
    networks:
      bigdata:
        ipv4_address: 172.25.0.11
    command: npm run start

volumes:
  postgres-data:

networks:
  bigdata:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1