version: '1'
name: school-system

services:
  Postgres:
    image: postgres:latest
    container_name: Postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../data/postgres-data:/var/lib/postgresql/data

  Nestjs:
    image: school-system-nest:latest
    container_name: Nestjs
    # build:
    #   context: ../
    #   dockerfile: backend.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../data/nestjs-data:/school-system-nest/nestjs-data/data
    links:
      - Postgres

  Ngnix:
    image: nginx:alpine
    container_name: Ngnix
    ports:
      - '80:80'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - Nestjs
